CREATE DATABASE FDevsQuiz;
USE [FDevsQuiz]
GO
/****** Object:  Table [dbo].[ALTERNATIVA]    Script Date: 26/05/2021 21:31:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALTERNATIVA](
	[CODIGOALTERNATIVA] [int] NOT NULL,
	[TITULO] [varchar](100) NULL,
	[CORRETA] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGOALTERNATIVA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERGUNTA]    Script Date: 26/05/2021 21:31:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERGUNTA](
	[CODIGOPERGUNTA] [int] NOT NULL,
	[TITULO] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGOPERGUNTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERGUNTA_ALTERNATIVA]    Script Date: 26/05/2021 21:31:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERGUNTA_ALTERNATIVA](
	[CODIGO] [int] NOT NULL,
	[CODIGOPERGUNTA] [int] NULL,
	[CODIGOALTERNATIVA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUIZ]    Script Date: 26/05/2021 21:31:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUIZ](
	[CODIGOQUIZ] [int] NOT NULL,
	[TITULO] [varchar](40) NULL,
	[NIVEL] [varchar](20) NULL,
	[IMAGEMURL] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGOQUIZ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUIZ_PERGUNTA]    Script Date: 26/05/2021 21:31:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUIZ_PERGUNTA](
	[CODIGOQUIZPERGUNTA] [int] NOT NULL,
	[CODIGOQUIZ] [int] NULL,
	[CODIGOPERGUNTA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGOQUIZPERGUNTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 26/05/2021 21:31:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[CODIGOUSUARIO] [decimal](18, 0) NOT NULL,
	[NOMEUSUARIO] [varchar](50) NULL,
	[PONTUACAO] [decimal](18, 0) NOT NULL,
	[IMAGEURL] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGOUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERGUNTA_ALTERNATIVA]  WITH CHECK ADD FOREIGN KEY([CODIGOPERGUNTA])
REFERENCES [dbo].[PERGUNTA] ([CODIGOPERGUNTA])
GO
ALTER TABLE [dbo].[PERGUNTA_ALTERNATIVA]  WITH CHECK ADD FOREIGN KEY([CODIGOALTERNATIVA])
REFERENCES [dbo].[ALTERNATIVA] ([CODIGOALTERNATIVA])
GO
ALTER TABLE [dbo].[QUIZ_PERGUNTA]  WITH CHECK ADD FOREIGN KEY([CODIGOPERGUNTA])
REFERENCES [dbo].[PERGUNTA] ([CODIGOPERGUNTA])
GO
ALTER TABLE [dbo].[QUIZ_PERGUNTA]  WITH CHECK ADD FOREIGN KEY([CODIGOQUIZ])
REFERENCES [dbo].[QUIZ] ([CODIGOQUIZ])
GO